services:
  - docker
language: java
jdk:
  - openjdk11
branches:
  only:
    - master
    - "/^(\d+\.)?(\d+\.)?\d+(-\w+)?$/"
cache:
    directories:
        - "$HOME/.m2"
install: true
script:
  - mvn -q clean package
